version: '3'
services:
  mongo:
    image: 'mongo'
    volumes:
      - db-data:/data/db
  node-app:
    build: .
    ports:
      - "3100:3100"
    volumes: 
      - /app/node_modules
      - .:/app
volumes:
  db-data:
