apiVersion: apps/v1
kind: Deployment
metadata:
  name: choumazon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: choumazon
  template:
    metadata:
      labels:
        app: choumazon
    spec:
      containers:
        - name: choumazon
          image: a88ttony/choumazon
          ports:
            - name: liveness-port
              containerPort: 3000
          env:
            - name: DATABASE_URL
              value: mongodb://mongo:27017
            - name: PORT
              value: "3000"
          livenessProbe:
            httpGet:
              path: /shops
              port: liveness-port
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /shops
              port: liveness-port
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: choumazon
spec:
  selector:
    app: choumazon
  type: NodePort
  ports:
    - port: 3001
      targetPort: 3000
      nodePort: 30390
